# CI de Nível 04 - disparo dos testes dentro do pipe de dev

#nome do nosso 'pipeline'
name: 'Execução Integrada'

#regras de disparo (gatilhos/triggers)
#podem ser a partir de um horario,mas iremos usar o trigger workflow_dispatch (execução manual)

on:
  workflow_dispatch:

#trabalhos/tarefas dentro do pipeline = jobs
jobs:
  inspecao:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    steps:
      #baixar o projeto, fazer o clone do repositorio para a máquina
      - uses: actions/checkout@v4
      #instalar o yarn
      - name: Instalando Yarn
        run: npm install -g yarn
      #instalar as dependencias
      - name: Instalando dependências
        run: yarn
      #checar a padronização do código
      - name: Checando padronização do código
        run: yarn lint

  unidade:
    #maquina que o job vai executar
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      #baixar o projeto, fazer o clone do repositorio para a máquina
      - uses: actions/checkout@v4
      #instalar o yarn
      - name: Instalando Yarn
        run: npm install -g yarn
      #instalar as dependencias
      - name: Instalando dependências
        run: yarn
      #checar a padronização do código
      - name: Executando testes de unidade
        run: yarn test

  e2e-testes:
    #maquina que o job vai executar
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação do Playwright (navegadores)
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

      # publicação dos relatórios
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report

  deploy:
    #maquina que o job vai executar
    runs-on: ubuntu-latest
    needs: [e2e-testes] # Aqui está o nome correto do job (com 'e' no final)

    steps:
      # simulação do deploy
      - name: Simulação do Deploy
        run: echo "simulando o deploy com sucesso"
